export const loadingScreenTitles = [
    "Loading... Grab a snack and get ready to shine brighter than the loading bar!",
    "Hold on tight! Our hamsters are running as fast as they can to power up your app.",
    "Loading... Making sure the pixels are in the right places. Patience, young Jedi.",
    "Just a moment... Imagine dragons. No, seriously, imagine dragons while we load.",
    "Loading... Counting to infinity. It might take a while, so feel free to grab a book.",
    "Hold your horses! Or unicorns. Whichever mythical creature you prefer. Almost there!",
    "Loading... Because good things come to those who wait, and great things to those who make loading screen jokes.",
    "Just a sec... If time travel was possible, this would be instant. Meanwhile, enjoy the suspense.",
    "Loading... Summoning the digital spirits to make your experience magical. Almost spellbound!",
    "Patience, Padawan... Yoda is optimizing the Force for a smoother loading experience.",
    "Loading... Brewing a cup of coffee for you. It'll be done before the caffeine kicks in!",
    "Hold on to your hats! Or, if you prefer, to your virtual reality headset. Loading awesomeness!",
    "Loading... Because Rome wasn’t built in a day, and neither was this fantastic app.",
    "Charging warp drive... Oops, wrong loading screen. But hey, almost as cool!",
    "Just a moment... It's not procrastination; it's optimization of anticipation.",
];
