import { Poppins, Quicksand } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "@/trpc/react";

import "@/styles/globals.css";

import { ThemeProvider } from "@/components/providers/theme-provider";

const poppins = Poppins({
    weight: ["400", "500", "600", "700"],
    subsets: ["latin"],
    variable: "--font-poppins",
});

const quicksand = Quicksand({
    subsets: ["latin"],
    variable: "--font-quicksand",
});

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

interface RootLayoutProps {
    children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`font-quicksand ${poppins.variable} ${quicksand.variable}`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    disableTransitionOnChange
                    enableSystem
                >
                    <TRPCReactProvider cookies={cookies().toString()}>
                        {children}
                    </TRPCReactProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
